### ISSUE TITLE
Allow multiple Connect API URLs per Connect cluster

### ISSUE THREAD

**Issue by vuldin** [redpanda-data/redpanda-ansible-collection#68]
It doesn’t appear that I can add multiple connect API URLs to a cluster. Most of the clusters were supported are distributed with multiple servers. Can this be confirmed and if so could this config be updated to support a list? 

 ```
connect:
  enabled: true
  clusters:
    - name: KFK-RND-RP
      url:["https://server1.domain:8083","https://server2.domain:8083","https://server3.domain:8083","https://server4.domain:8083"] # Multiple URLs breaks loading the connect cluster in the UI
```
